### ISSUE TITLE
Shortcuts to navigate to the top/bottom of the window

### ISSUE THREAD

**Issue by carun** [andrewshadura/git-crecord#18]
Typically the shortcuts used in `man`, `less`, `more` and such tools are very handy. Similarly, it would be nice if we can use such shortcuts for navigation in crecord.

* `G` to navigate to the bottom
* `g` to navigate to the top.

**Comment by andrewshadura** [comment]
Good idea, thanks!

**Comment by andrewshadura** [comment]
Fixed in 05710f6
