### ISSUE TITLE
Unintuitive (buggy?) staging behavior / inconsistent documentation

### ISSUE THREAD

**Issue by waldyrious** [andrewshadura/git-crecord#41]
I use `git add -p` a lot to stage individual hunks before creating a commit, so I tried to replicate that flow using `git crecord`. Since the README only mentions the `crecord` subcommand (which is also the name of the project), I assumed it was the only one available.

Once inside the `git crecord` interface, I used the quick help message at the top, which [says](https://github.com/andrewshadura/git-crecord/blob/8c364ae7f071133efa10c9b8ae5b5a074339aab4/git_crecord/chunk_selector.py#L595) that the <kbd>c</kbd> keystroke "confirms" the present selection. However, when I did that, I was immediately brought to a text editor to write a commit message. I saved an empty message to abort the commit, expecting the changes to remain staged, only to find that the selection I had made was lost.

I then tried again, and pressed <kbd>?</kbd> to open the extended help message, which [says](https://github.com/andrewshadura/git-crecord/blob/8c364ae7f071133efa10c9b8ae5b5a074339aab4/git_crecord/chunk_selector.py#L1018) that <kbd>c</kbd> actually stands for "commit", and <kbd>s</kbd> is the keystroke I should use for staging. So I tried that, but the behavior was the same: I was dropped into an editor to write a commit message, and exiting with an empty message still didn't keep my changes staged.

There are a few issues here:

1. The short help message doesn't make it clear that pressing <kbd>c</kbd> will instanty initiate a commit. That was surprising behavior. 
2. If I run `git crecord` and press <kbd>c</kbd> after making a selection, and then choose to abort the commit, the changes should either remain staged, or I should at least be offered the option to make them so, to prevent losing the selection I had made.
3. Confusing documentation: the short and extended help messages should be consistent about the meaning of pressing <kbd>c</kbd> (commit vs confirm selection). Also, the README makes no mention of the other subcommands (which I assume might be the intended way to initiate a non-commit action?)
4. If I press the <kbd>s</kbd> key, I should not be prompted to make a commit at all.
5. If I abort the commit after pressing <kbd>s</kbd>, the selection should **definitely** remain staged!

I'm not sure how many of these are the result of bugs, of me misunderstanding the usage of the tool, or something else, which is why I didn't open separate issues for each of the problems I listed above. Let me know if you'd like me to do so! :)

**Comment by waldyrious** [comment]
For the record, the version of `git crecord` I'm using is `20201025.0`.

**Comment by andrewshadura** [comment]
You’re right about staging, it’s never been finished, but there’s very little missing until it’s usable.

I’m not quite sure thought what behaviour would your expect of `c`, what other operation would that initiate if not committing? In fact, I had an intermediate confirmation step which I was asked to disable by default, but it can be re-enabled with `--confirm`.

**Comment by andrewshadura** [comment]
Right, I think I see what you mean. The help text should say `c` is for committing, not confirmation.
