### ISSUE TITLE
Is staging working?

### ISSUE THREAD

**Issue by maelvalais** [andrewshadura/git-crecord#8]
Hi,

When I tried Mercurial for the first time a couple of months ago, I was astonished to see how much more convenient the `hg record` (in fact, it is `crecord`) over the poor UI of `git add -p`. So I looked around to see if someone had tried to port crecord to git. This project does exactly that and it seems very promising!

When I selected some hunks though and typed `s` (stage), vim opens for typing a commit message.
Also, how hard would it be to have the currently staged state when opening `git crecord`?

Thanks again,

Maël

**Comment by andrewshadura** [comment]
This is WIP at the moment as #5.
